name: constant
description: constant
outputs:
  java-version:
    value: ${{ steps.constant.outputs.java-version }}
  java-distribution:
    value: ${{ steps.constant.outputs.java-distribution }}
  gradle-version:
    value: ${{ steps.constant.outputs.gradle-version }}
  aws-region:
    value: ${{ steps.constant.outputs.aws-region }}
runs:
  using: composite
  steps:
    - id: constant
      run: |        
        echo "java-version=17" >> $GITHUB_OUTPUT
        echo "java-distribution=temurin" >> $GITHUB_OUTPUT
        echo "gradle-version=7.4.2" >> $GITHUB_OUTPUT
        echo "aws-region=ap-northeast-1" >> $GITHUB_OUTPUT
      shell: bash
