openapi: 3.0.0
info:
  title: kiwa-api
  description: api created by ningenme
  version: 1.0.0
servers:
  - url: https://kiwa-api.ningenme.net
paths:
  /healthcheck:
    $ref: './paths/Healthcheck.yaml'
  /users:
    $ref: './paths/Users.yaml'
  /users/me:
    $ref: './paths/UsersMe.yaml'
  /login:
    $ref: './paths/Login.yaml'
