openapi: 3.0.0
info:
  title: kiwa-api
  description: api created by ningenme
  version: 1.0.0
servers:
  - url: https://kiwa-api.ningenme.net
paths:
  /healthcheck:
    $ref: './paths/Healthcheck.yaml'
  /users:
    $ref: './paths/Users.yaml'
# TODO
# POST /users
# POST /login
# GET /users/me
# POST /logout
