logging:
  level:
    root: debug
spring:
  datasource:
    url: ${NINGENME_MYSQL_URL:jdbc:mysql://localhost:3306}/auth?enabledTLSProtocols=TLSv1.2
    username: ${NINGENME_MYSQL_MASTER_USER_USERNAME:root}
    password: ${NINGENME_MYSQL_MASTER_USER_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
