logging:
  level:
    root: debug
spring:
  datasource:
    url: jdbc:mysql://${NINGENME_MYSQL_HOST:localhost}:${NINGENME_MYSQL_PORT:3306}/auth?enabledTLSProtocols=TLSv1.2
    username: ${NINGENME_MYSQL_MASTER_USER_USERNAME:root}
    password: ${NINGENME_MYSQL_MASTER_USER_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${NINGENME_REDIS_HOST:localhost}
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
