/* tslint:disable */
/* eslint-disable */
/**
 * kiwa-api
 * api created by ningenme
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthcheckGetResponse
 */
export interface HealthcheckGetResponse {
    /**
     * 
     * @type {string}
     * @memberof HealthcheckGetResponse
     */
    message: string;
}

/**
 * Check if a given object implements the HealthcheckGetResponse interface.
 */
export function instanceOfHealthcheckGetResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function HealthcheckGetResponseFromJSON(json: any): HealthcheckGetResponse {
    return HealthcheckGetResponseFromJSONTyped(json, false);
}

export function HealthcheckGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthcheckGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function HealthcheckGetResponseToJSON(value?: HealthcheckGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

