/*
kiwa-api

api created by ningenme

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LoginPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginPostResponse{}

// LoginPostResponse struct for LoginPostResponse
type LoginPostResponse struct {
	Message string `json:"message"`
}

// NewLoginPostResponse instantiates a new LoginPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginPostResponse(message string) *LoginPostResponse {
	this := LoginPostResponse{}
	this.Message = message
	return &this
}

// NewLoginPostResponseWithDefaults instantiates a new LoginPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginPostResponseWithDefaults() *LoginPostResponse {
	this := LoginPostResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *LoginPostResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *LoginPostResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *LoginPostResponse) SetMessage(v string) {
	o.Message = v
}

func (o LoginPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

type NullableLoginPostResponse struct {
	value *LoginPostResponse
	isSet bool
}

func (v NullableLoginPostResponse) Get() *LoginPostResponse {
	return v.value
}

func (v *NullableLoginPostResponse) Set(val *LoginPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginPostResponse(val *LoginPostResponse) *NullableLoginPostResponse {
	return &NullableLoginPostResponse{value: val, isSet: true}
}

func (v NullableLoginPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


