/*
kiwa-api

api created by ningenme

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UsersMeGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersMeGetResponse{}

// UsersMeGetResponse struct for UsersMeGetResponse
type UsersMeGetResponse struct {
	UserId string `json:"userId"`
	Authority UsersMeGetResponseAuthority `json:"authority"`
}

// NewUsersMeGetResponse instantiates a new UsersMeGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersMeGetResponse(userId string, authority UsersMeGetResponseAuthority) *UsersMeGetResponse {
	this := UsersMeGetResponse{}
	this.UserId = userId
	this.Authority = authority
	return &this
}

// NewUsersMeGetResponseWithDefaults instantiates a new UsersMeGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersMeGetResponseWithDefaults() *UsersMeGetResponse {
	this := UsersMeGetResponse{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UsersMeGetResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UsersMeGetResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UsersMeGetResponse) SetUserId(v string) {
	o.UserId = v
}

// GetAuthority returns the Authority field value
func (o *UsersMeGetResponse) GetAuthority() UsersMeGetResponseAuthority {
	if o == nil {
		var ret UsersMeGetResponseAuthority
		return ret
	}

	return o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value
// and a boolean to check if the value has been set.
func (o *UsersMeGetResponse) GetAuthorityOk() (*UsersMeGetResponseAuthority, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authority, true
}

// SetAuthority sets field value
func (o *UsersMeGetResponse) SetAuthority(v UsersMeGetResponseAuthority) {
	o.Authority = v
}

func (o UsersMeGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersMeGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["authority"] = o.Authority
	return toSerialize, nil
}

type NullableUsersMeGetResponse struct {
	value *UsersMeGetResponse
	isSet bool
}

func (v NullableUsersMeGetResponse) Get() *UsersMeGetResponse {
	return v.value
}

func (v *NullableUsersMeGetResponse) Set(val *UsersMeGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersMeGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersMeGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersMeGetResponse(val *UsersMeGetResponse) *NullableUsersMeGetResponse {
	return &NullableUsersMeGetResponse{value: val, isSet: true}
}

func (v NullableUsersMeGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersMeGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


