/*
kiwa-api

api created by ningenme

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UsersPostResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPostResponse{}

// UsersPostResponse struct for UsersPostResponse
type UsersPostResponse struct {
	Message string `json:"message"`
}

// NewUsersPostResponse instantiates a new UsersPostResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPostResponse(message string) *UsersPostResponse {
	this := UsersPostResponse{}
	this.Message = message
	return &this
}

// NewUsersPostResponseWithDefaults instantiates a new UsersPostResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPostResponseWithDefaults() *UsersPostResponse {
	this := UsersPostResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *UsersPostResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *UsersPostResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *UsersPostResponse) SetMessage(v string) {
	o.Message = v
}

func (o UsersPostResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPostResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

type NullableUsersPostResponse struct {
	value *UsersPostResponse
	isSet bool
}

func (v NullableUsersPostResponse) Get() *UsersPostResponse {
	return v.value
}

func (v *NullableUsersPostResponse) Set(val *UsersPostResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPostResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPostResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPostResponse(val *UsersPostResponse) *NullableUsersPostResponse {
	return &NullableUsersPostResponse{value: val, isSet: true}
}

func (v NullableUsersPostResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPostResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


