/* tslint:disable */
/* eslint-disable */
/**
 * kiwa-api
 * api created by ningenme
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthcheckGetResponse,
} from '../models';
import {
    HealthcheckGetResponseFromJSON,
    HealthcheckGetResponseToJSON,
} from '../models';

/**
 * 
 */
export class HealthcheckApi extends runtime.BaseAPI {

    /**
     */
    async healthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthcheckGetResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/healthcheck`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthcheckGetResponseFromJSON(jsonValue));
    }

    /**
     */
    async healthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthcheckGetResponse> {
        const response = await this.healthGetRaw(initOverrides);
        return await response.value();
    }

}
