name: api-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.constant.outputs.java-version }}
      java-distribution: ${{ steps.constant.outputs.java-distribution }}
      gradle-version: ${{ steps.constant.outputs.gradle-version }}
      aws-region: ${{ steps.constant.outputs.aws-region }}
      aws-ecr-repository: kiwa-api-repository
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: constant
        name: constant
        uses: ./.github/workflows/composite/constant

  gradle-check:
    runs-on: ubuntu-latest
    name: gradle-check
    needs: [ constant ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: setup-java
        name: setup java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ needs.constant.outputs.java-version }}
          distribution: ${{ needs.constant.outputs.java-distribution }}
      - name: gradle check
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean check
          gradle-version: ${{ needs.constant.outputs.gradle-version }}

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [ constant, gradle-check ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: build-and-push-image
        name: build and push image
        uses: ./.github/workflows/composite/build-and-push-image
        with:
          java-version: ${{ needs.constant.outputs.java-version }}
          java-distribution: ${{ needs.constant.outputs.java-distribution }}
          gradle-version: ${{ needs.constant.outputs.gradle-version }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ needs.constant.outputs.aws-region }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          aws-ecr-repository: ${{ needs.constant.outputs.aws-ecr-repository }}
