name: api-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      aws-region: ${{ steps.constant.outputs.aws-region }}
      docker-image-name: kiwa-api-repository:${{ github.sha }}
      java-version: ${{ steps.constant.outputs.java-version }}
      java-distribution: ${{ steps.constant.outputs.java-distribution }}
      gradle-version: ${{ steps.constant.outputs.gradle-version }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: constant
        name: constant
        uses: ningenMe/chiyuki-k8s-config/action/constant@main

  gradle-check:
    runs-on: ubuntu-latest
    name: gradle-check
    needs: [ constant ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: setup-java
        name: setup java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: ${{ needs.constant.outputs.java-version }}
          distribution: ${{ needs.constant.outputs.java-distribution }}
      - name: gradle check
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: clean check
          gradle-version: ${{ needs.constant.outputs.gradle-version }}
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [ constant, gradle-check ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: build-gradle
        name: build-gradle
        uses: ningenMe/chiyuki-k8s-config/action/build-gradle@main
        with:
          java-version: ${{ needs.constant.outputs.java-version }}
          java-distribution: ${{ needs.constant.outputs.java-distribution }}
          gradle-version: ${{ needs.constant.outputs.gradle-version }}
      - id: docker-image-push
        name: docker-image-push
        uses: ningenMe/chiyuki-k8s-config/action/docker-image-push@main
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ needs.constant.outputs.aws-region }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          docker-image-name: ${{ needs.constant.outputs.docker-image-name }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ constant, build-and-push-image ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: kick-deploy
        name: kick deploy
        uses: ningenMe/chiyuki-k8s-config/action/kick-deploy@main
        with:
          deploy-token: ${{ secrets.DEPLOY_TOKEN }}
          application-name: kiwa-api